version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_USER
      - MYSQL_DATABASE=$DB_PASS
    ports:
      - $MYSQLDB_LOCAL_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true
volumes:
  db:
