version: '3.8'

services:
  # DB
  mysqldb:
    container_name: marketing-db
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysqldb
    networks:
      - main-net

  # DB GUI
  phpmyadmin:
    container_name: marketing-db-gui
    depends_on:
      - mysqldb
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    env_file: ./.env
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: $DB_PASS
    networks:
      - main-net

  # Main App
  nodejs:
    container_name: marketing-api
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASS
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    networks:
      - main-net
    stdin_open: true
    tty: true
volumes:
  db:
networks:
  main-net:
